[package]
name = "hdb"
version = "0.1.0"
authors = ["Justin Guidroz <justin.guidroz@gmail.com>"]

[features]
with-openssl = ["openssl"]

[dependencies]
openssl = { version = "0.9", optional = true }
postgres = { version = "0.14", features = ["with-openssl"] }
serde = "1.0"
serde_derive = "1.0"
